name: Deploy html to GitHub Pages
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]
    paths-ignore:
      - ".github/**"

  push:
    branches:
      - main
      - develop
    paths-ignore:
      - ".github/**"

permissions:
  deployments: write
  id-token: write
  contents: write
  pull-requests: write

jobs:
  build:
    if: github.event_name == 'pull_request' && github.event.action != 'closed' || github.event_name == 'push'
    runs-on: ubuntu-latest
    timeout-minutes: 10
    outputs:
      directory: ${{ steps.set-environment.outputs.directory }}

    steps:
      - name: Start deployment
        # https://github.com/bobheadxi/deployments/tree/v1/
        uses: bobheadxi/deployments@648679e8e4915b27893bd7dbc35cb504dc915bc8
        id: deployment
        with:
          step: start
          token: ${{ secrets.GITHUB_TOKEN }}
          env: PR-${{ github.event.number }}
          ref: ${{ github.head_ref}}

      # https://github.com/actions/checkout/tree/v4/
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
        with:
          fetch-depth: 1

      - name: Set environment variable
        id: set-environment
        run: |

          # PR時
          if [ -n "${{ github.event.number }}" ]; then
            DIRECTORY=${{ github.event.number }}
          else
            # ブランチ名
            DIRECTORY=${{ github.ref_name }}
          fi
          echo "directory=$DIRECTORY" >> $GITHUB_OUTPUT
          echo "base_url=https://example.com/$DIRECTORY" >> $GITHUB_OUTPUT
          echo "DIRECTORY: $DIRECTORY"
          echo "BASE_URL: https://example.com/$DIRECTORY"

      # https://github.com/actions/upload-artifact/tree/v4/
      - uses: actions/upload-artifact@0b2256b8c012f0828dc542b3febcab082c67f72b
        with:
          name: html
          path: ./index.html

  deploy:
    if: github.event_name == 'pull_request' && github.event.action != 'closed' || github.event_name == 'push'
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: clone
        uses: actions/checkout@v4
        with:
          ref: gh-pages

      - name: Download Artifact
        # https://github.com/actions/download-artifact/tree/v4/
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16
        with:
          name: html
          path: ${{ needs.build.outputs.directory }}

      - name: List files
        run: ls -lah ${{ needs.build.outputs.directory }}

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add -N .
          if ! git diff --exit-code --quiet
          then
            git commit -m "Deploy ${{ needs.build.outputs.directory }} to GitHub Pages"
            git push origin gh-pages
          fi

      - name: Comment PullRequest
        if: github.event_name == 'pull_request'
        uses: JoseThen/comment-pr@v1.2.0
        with:
          comment: "Preview ${{ steps.deployment.outputs.page_url }}"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}

  deactivate-on-close:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Set environment variable
        id: set-environment
        run: echo "directory=${{ github.event.number }}" >> $GITHUB_OUTPUT

      - name: clone
        uses: actions/checkout@v4
        with:
          ref: gh-pages

      - name: Delete old files in gh-pages
        run: |
          DIRECTORY=${{ steps.set-environment.outputs.directory }}
          rm -rf $DIRECTORY
          echo "Deleted $DIRECTORY"

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "Deactivate ${{ steps.set-environment.outputs.directory }} environment"
          git push origin gh-pages

      - name: Update deployment status
        # https://github.com/bobheadxi/deployments/tree/v1/
        uses: bobheadxi/deployments@648679e8e4915b27893bd7dbc35cb504dc915bc8
        with:
          step: deactivate-env
          token: ${{ secrets.GITHUB_TOKEN }}
          env: PR-${{ github.event.number }}
          desc: "PR-${{ github.event.number }} environment has been deactivated."
